# -*- coding: utf-8 -*-
"""Untitled82.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOfFQQ7EcpNvXuNYCIlrjqSEl7T-T5cl
"""

import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import sys


# Load datasets
def load_data(meta_path, embed_path):
    try:
        meta_df = pd.read_excel(meta_path)
        bert_df = pd.read_excel(embed_path)
        bert_df = bert_df.drop(columns=["Plot Synopsis"], errors="ignore")
        return meta_df, bert_df
    except FileNotFoundError:
        print("Dataset files not found")
        sys.exit(1)


# Preprocess
def preprocess(meta_df, bert_df):
    numerical_vars = [
        "budget", "Duration_Minutes", "First Actor Avg",
        "Second Actor Avg", "Average IMDb Rating"
    ]

    categorical_vars = ["MPA", "1st Genre", "First Production Company"]

    # Category Reduction
    meta_df["MPA"] = meta_df["MPA"].apply(
        lambda x: x if x in ["PG-13", "R", "PG"] else "Other"
    )

    main_genres = [
        "Action", "Drama", "Comedy", "Biography",
        "Crime", "Adventure", "Horror"
    ]
    meta_df["1st Genre"] = meta_df["1st Genre"].apply(
        lambda x: x if x in main_genres else "Other"
    )

    main_companies = [
        "Columbia Pictures", "Universal Pictures", "Warner Bros.",
        "Paramount Pictures", "Twentieth Century Fox", "New Line Cinema"
    ]
    meta_df["First Production Company"] = meta_df[
        "First Production Company"
    ].apply(lambda x: x if x in main_companies else "Other")

    # One-hot encoding
    if sklearn.__version__ >= "1.2":
        encoder = OneHotEncoder(drop="first", sparse_output=False, handle_unknown="ignore")
    else:
        encoder = OneHotEncoder(drop="first", sparse=False, handle_unknown="ignore")

    encoded = encoder.fit_transform(meta_df[categorical_vars])
    encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_vars))

    bert_df.columns = bert_df.columns.astype(str)

    X = pd.concat([
        meta_df[numerical_vars].reset_index(drop=True),
        encoded_df.reset_index(drop=True),
        bert_df.reset_index(drop=True).drop(columns=["Title"], errors="ignore")
    ], axis=1)

    y_str = meta_df["Rating"].apply(lambda r: "Success" if r >= 6.5 else "Unsuccess")

    le = LabelEncoder()
    y = le.fit_transform(y_str)

    return X, y, le


# Train model
def train_model(X, y):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)
    return model, X_test, y_test


def main():
    META_FILE = "Final Dataset.xlsx"
    EMBED_FILE = "longformer_embeddings.xlsx"

    meta_df, bert_df = load_data(META_FILE, EMBED_FILE)

    X, y, label_encoder = preprocess(meta_df, bert_df)

    model, X_test, y_test = train_model(X, y)

    y_pred = model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))


if __name__ == "__main__":
    main()